CREATE TABLE stores(
	store_id BIGINT NOT NULL AUTO_INCREMENT,
	store_name VARCHAR(50) NOT NULL,
	is_deleted TINYINT(1) NOT NULL DEFAULT 0,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(store_id)
);

CREATE TABLE products(
	product_id BIGINT NOT NULL AUTO_INCREMENT,
	store_id BIGINT NOT NULL,
	name VARCHAR(50) NOT NULL,
	description VARCHAR(100),
	sku VARCHAR(10) NOT NULL,
	price DECIMAL(10,2) NOT NULL DEFAULT 0,
	is_deleted TINYINT(1) NOT NULL DEFAULT 0,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(product_id)
);

CREATE TABLE stock(
	product_id BIGINT NOT NULL,
	store_id BIGINT NOT NULL,
	count INT(11) NOT NULL DEFAULT 0,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(product_id, store_id)
);

CREATE TABLE orders(
	order_id BIGINT NOT NULL AUTO_INCREMENT,
	order_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	status TINYINT(1) NOT NULL DEFAULT 0,
	first_name VARCHAR(50),
	last_name VARCHAR(50),
	email VARCHAR(100),
	phone VARCHAR(10),
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(order_id)
);

CREATE TABLE product_order(
	order_id BIGINT NOT NULL,
	store_id BIGINT NOT NULL,
	product_id BIGINT NOT NULL,
	created_date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	updated_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

